name: buzz_widgets
description: buzz widgets are utility ui components to minimize duplication.
version: 0.0.1
homepage: https://github.com/abbas-alshafai/buzz_widgets

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  buzz_result:
    git:
      ref: master
      url: https://github.com/abbas-alshafai/buzz_result
  buzz_utils:
    git:
      ref: master
      url: https://github.com/abbas-alshafai/buzz_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter: